baseURL: https://aotingxu.github.io/
theme: pure
title: 敖廷旭的博客
defaultContentLanguage: zh  # en/zh/...
footnoteReturnLinkContents: ↩
hasCJKLanguage: true
paginate: 7
enableEmoji: true
PygmentsCodeFences: false
googleAnalytics: ""      # UA-XXXXXXXX-X 
permalinks:
  posts: /:year/:month/:filename/

taxonomies:
    category : categories
    tag : tags
    series : series
outputFormats:          # use for search. recommend not to modify 
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
    home: ["HTML","RSS","SearchIndex"]  # recommend not to modify
# sitemap
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  main:
    - identifier: home
      name: Home
      title: 主页
      url: /
      weight: 1

    - identifier: archives
      name: Archives
      title: 归档
      url: /posts/
      weight: 2

    - identifier: categories
      name: Categories
      title: 分类
      url: /categories/
      weight: 3

    - identifier: tags
      name: Tags
      title: 标签
      url: /tags/
      weight: 4

    - identifier: about
      name: About
      title: 关于
      url: /about/
      weight: 5


params:
  since: 2019
  dateFormatToUse: "2006-01-02"
  enablePostCopyright: true
  # the directory under content folder that you want to render
  mainSections: ["posts"]
  # Enable/Disable menu icons
  # Icon Reference: http://blog.cofess.com/hexo-theme-pure/iconfont/demo_fontclass.html
  enableMathJax: true #Enable mathjax support, to use mathematical notations
  highlightjs:
    langs: ["python", "javascript"] # refer to http://staticfile.org/, search highlight.js, already have highlight.min.js

  # Allows you to specify an override stylesheet
  # put custom.css in $hugo_root_dir/static/
  # customCSS: css/custom.css

  menuIcons:
    enable: true  # 是否启用导航菜单图标
    home: icon-home-fill
    archives: icon-archives-fill
    categories: icon-folder
    tags: icon-tags
    repository: icon-project
    books: icon-book-fill
    links: icon-friendship
    about: icon-cup-fill

  # profile
  profile:
    enabled: true # Whether to show profile bar
    avatar: personal.jpg
    gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
    author: 敖廷旭
    author_title: 菜鸟慢慢成长
    author_description: 心有猛虎，细嗅蔷薇
    location: Shanghai, China
    follow: https://github.com/aotingxu
    # Social Links
    social:
      links:
        twitter: https://twitter.com/Aotin626x
        facebook: https://www.facebook.com/100037008668968
        github: https://github.com/aotingxu
        weibo: https://www.weibo.com/atx0626
        rss: /index.xml
      link_tooltip: true # enable the social link tooltip, options: true, false
  # Site
  site:
    logo:
      enabled: true
      width: 40
      height: 40
      url: favicon.ico
    title: Hugo # 页面title
    favicon: favicon.ico
    board: <p>let's go!</p> # 公告牌

  # Share
  # weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
  share:
    enable: true # 是否启用分享
    sites: weibo,qq,wechat,facebook,twitter # PC端显示的分享图标
    mobile_sites: weibo,qq,qzone # 移动端显示的分享图标

  # Comment
  comment:
    type:  gitalk # type disqus/gitalk/valine 启用哪种评论系统
    disqus:  # enter disqus shortname here
    gitalk: # gitalk. https://gitalk.github.io/
      owner: aotingxu #必须. GitHub repository 所有者，可以是个人或者组织。
      admin: aotingxu #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
      repo:  https://github.com/aotingxu/aotingxu.github.io.git #必须. GitHub repository.
      ClientID: 7932ad4755e175ddc87a #必须. GitHub Application Client ID.
      ClientSecret: 082f3c7aced7f778e76035458d38e5abb81c4d43 #必须. GitHub Application Client Secret.
    valine: # Valine. https://valine.js.org
      appid: # your leancloud application appid
      appkey: # your leancloud application appkey
      notify: # mail notifier , https://github.com/xCss/Valine/wiki
      verify: # Verification code
      placeholder: enjoy~ # comment box placeholder
      avatar: mm # gravatar style
      meta: nick,mail # custom comment header
      pageSize: 10 # pagination size
      visitor: false # Article reading statistic https://valine.js.org/visitor.html

  # Donate
  donate:
    enable: true
    # 微信打赏
    wechatpay:
      qrcode: donate/wechat.jpg
      title: 微信支付
    # 支付宝打赏
    alipay:
      qrcode: donate/alipay.jpg
      title: 支付宝

  # PV
  pv:
    busuanzi:
      enable: false # 不蒜子统计
    leancloud:
      enable: false # leancloud统计
      app_id: # leancloud <AppID>
      app_key: # leancloud <AppKey>

  # wordcount
  postCount:
    enable: true
    wordcount: true # 文章字数统计
    min2read: true # read time 阅读时长预计

  # config
  config:
    skin: theme-white # theme color default is white. other type [theme-black,theme-blue,theme-green,theme-purple]
    layout: main-center # main-left main-center main-right
    excerpt_link: Read More
    toc: true

  # Sidebar
  sidebar: right

  # Search
  search:
    enable: true # enable search. thanks for https://raw.githubusercontent.com/ppoffice/hexo-theme-icarus/master/source/js/insight.js

  # Sidebar only the following widgets. you can remove any you don't like it.
  widgets:
    - board
    - category
    - tag
    - recent_posts

# publishDir = docs